/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import clases.PhotoViewer;
import javax.swing.JFrame;

/**
 *
 * @author Cristhian
 */
public class EleccionAgregar extends javax.swing.JFrame {
   
    private String Usuario;
    private PhotoViewer photoViewer ;
JFPrincipal ventanaAtras;
    public void setVentanaAtras(JFPrincipal ventanaAtras) {
        this.ventanaAtras = ventanaAtras;
    }
    
    public EleccionAgregar() {
        initComponents();
    }

    public PhotoViewer getPhotoViewer() {
        return photoViewer;
    }

    public void setPhotoViewer(PhotoViewer photoViewer) {
        this.photoViewer = photoViewer;
    }
    
    public void setUsuario(String nombreUsuario) {
        this.Usuario = nombreUsuario;
    }    

    public String getUsuario() {
        return Usuario;
    }
    
    private void destruirActividad(){
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonFoto = new javax.swing.JButton();
        botonAlbum = new javax.swing.JButton();
        botonPersona = new javax.swing.JButton();
        botonCamara = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonFoto.setText("FOTO");
        botonFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonFotoMouseClicked(evt);
            }
        });

        botonAlbum.setText("ALBUM");
        botonAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAlbumMouseClicked(evt);
            }
        });

        botonPersona.setText("PERSONA");
        botonPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPersonaMouseClicked(evt);
            }
        });

        botonCamara.setText("CAMARA");
        botonCamara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCamaraMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR");

        jButton1.setText("Atras");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCamara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonFoto)
                .addGap(18, 18, 18)
                .addComponent(botonAlbum)
                .addGap(18, 18, 18)
                .addComponent(botonPersona)
                .addGap(18, 18, 18)
                .addComponent(botonCamara)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFotoMouseClicked
        IngresarFoto agregarFoto = new IngresarFoto();
        agregarFoto.setUsuario(Usuario);
        agregarFoto.setPhotoViewer(photoViewer);
        agregarFoto.setVisible(true);
        agregarFoto.setVentanaAtras(this.ventanaAtras);
        destruirActividad();
    }//GEN-LAST:event_botonFotoMouseClicked

    private void botonAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAlbumMouseClicked
     IngresarAlbum agregarAlbum= new IngresarAlbum();
        agregarAlbum.setUsuario(Usuario);
        agregarAlbum.setPhotoViewer(photoViewer);
        agregarAlbum.setVisible(true);
        agregarAlbum.setVentanaAtras(this.ventanaAtras);
        destruirActividad();
    }//GEN-LAST:event_botonAlbumMouseClicked

    private void botonPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPersonaMouseClicked
       IngresarPersona agregarPersona= new IngresarPersona();
        agregarPersona.setUsuario(Usuario);
        agregarPersona.setPhotoViewer(photoViewer);
        agregarPersona.setVisible(true);
        agregarPersona.setVentanaAtras(this.ventanaAtras);
        destruirActividad();
    }//GEN-LAST:event_botonPersonaMouseClicked

    private void botonCamaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCamaraMouseClicked
     IngresarCamara agregarCamara= new IngresarCamara();
        agregarCamara.setUsuario(Usuario);
        agregarCamara.setPhotoViewer(photoViewer);
        agregarCamara.setVisible(true);
        agregarCamara.setVentanaAtras(this.ventanaAtras);
        
        destruirActividad();
    }//GEN-LAST:event_botonCamaraMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       this.ventanaAtras.setVisible(true);
        this.setVisible(false);
        this.dispose();
    
    }//GEN-LAST:event_jButton1MouseClicked
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleccionAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleccionAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleccionAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleccionAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleccionAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlbum;
    private javax.swing.JButton botonCamara;
    private javax.swing.JButton botonFoto;
    private javax.swing.JButton botonPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
